#!/bin/sh
################################################################
# Begin $rc_base/init.d/
#
# Description : 
# 
# Authors     :
# 
# Version     : 00.00
#
# Notes       :
#
###############################################################

. /etc/default/rc
. ${rc_functions}

case "$1" in
  pre)
	boot_msg "Configuring lighttpd for FABUI."
	/usr/sbin/lighttpd-enable-mod fastcgi fastcgi-php fabui
	evaluate_retval

	# TODO: configure mysql
	;;
  post)
	;;
  *)
	echo "Usage: $0 {pre|post}"
	exit 1
esac

exit $?
