#!/bin/env python
# -*- coding: utf-8; -*-
#
# (c) 2016 FABtotum, http://www.fabtotum.com
#
# This file is part of FABUI.
#
# FABUI is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# FABUI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FABUI.  If not, see <http://www.gnu.org/licenses/>.

# Import standard python module
import re


def process_line(line):
    attrs = {}
    
    if re.search('generated by Slic3r', line):
       attrs['slicer'] = 'SLIC3R'

    tags = line.split(';')

    if len(tags) == 2:
        # Available only if 'Verbose G-Code [x]' is selected
        if re.search('move to next layer', tags[1]):
            m = re.search('\((?P<layer>[0-9]+)\)',tags[1])
            if m:
                attrs['layer'] = m.group('layer')

    return attrs

