<?php 
defined('BASEPATH') OR exit('No direct script access allowed');
/***
 * 
 * 
 */
$config['javascript']['mandatory'] = array(
	'/assets/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js',
	'/assets/js/bootstrap/bootstrap.min.js',
	'/assets/js/notification/SmartNotification.min.js',
	'/assets/js/notification/FabtotumNotification.js',
	'/assets/js/smartwidgets/jarvis.widget.min.js',
	'/assets/js/plugin/msie-fix/jquery.mb.browser.min.js',
	'/assets/js/plugin/fastclick/fastclick.min.js',
	'/assets/js/plugin/noUiSlider.8.2.1/nouislider.min.js',
	'/assets/js/plugin/wNumb/wNumb.js',
	'/assets/js/plugin/jquery-websocket/jquery.WebSocket.js',
	'/assets/js/std/raphael.js',
	'/assets/js/std/modernizr-touch.js',
	'/assets/js/std/jogcontrols.js',
	'/assets/js/app.min.js',
	'/assets/js/fab.app.js',
	'/assets/js/plugin/bootstrap-tour/bootstrap-tour.js',
	'/assets/js/fabtotum.js'
);
/***
 * 
 * 
 */
$config['css']['mandatory'] = array(
	'/assets/css/bootstrap.min.css',
	'/assets/css/font-awesome.min.css',
	'/assets/css/line-icons-pro/styles.css',
	'/assets/css/smartadmin-production-plugins.min.css',
	'/assets/css/smartadmin-production.min.css',
	'/assets/css/smartadmin-skins.min.css',
	'/assets/css/font-fabtotum.css',
	'/assets/css/fonts.css',
	'/assets/css/demo.min.css',
	'/assets/css/bootstrap-tour/bootstrap-tour.min.css',
	'/assets/css/fabtotum.css',
	'/assets/js/plugin/noUiSlider.8.2.1/nouislider.min.css',
	'/assets/js/plugin/noUiSlider.8.2.1/nouislider.pips.css',
	'/assets/js/plugin/fancybox/jquery.fancybox.css',
	'/assets/css/third_party.css'
);
?>
