#!/bin/bash

# quit if we're called for the loopback
if [ "$IFACE" = lo ]; then
    echo "iface is loopback"
    exit 0
fi

do_post_up()
{
    DEFAULT="lo"

    for i in $(ifquery --state); do
        IFACE=$( echo ${i} | awk -F "=" '{print $1}' )

        if [ "x$DEFAULT" != x"wlan0" ]; then
            if [ x"$IFACE" == "wlan0" ]; then
                hostapd_cli -p /run/hostapd -i$IFACE get_config &> /dev/null
                if [ "$?" == "0" ]; then
                    continue
                fi
            fi
            DEFAULT=$IFACE
        fi
    done

    if [ x"$DEFAULT" == x"lo" ]; then
        exit 0
    fi

    GW=$(route -n  | grep $DEFAULT | grep UG | awk 'NR==1{print $2}')

    echo $DEFAULT
    echo $GW

    if [ x"$GW" == x"" ]; then
        exit 0
    fi

    for i in $(ifquery --state); do
        IFACE=$( echo ${i} | awk -F "=" '{print $1}' )

        if [ "x$IFACE" != x"lo" ]; then
            ip route delete default dev $IFACE
        fi
    done


    ip route add default via $GW
}

case $MODE in
    start)
        case $PHASE in
            pre-up)
                ;;
            post-up)
                do_post_up
                ;;
            *)
                ;;
        esac
        ;;
    stop)
        case $PHASE in
            pre-down)
                ;;
            post-down)
                ;;
            *)
                ;;
        esac
        ;;
    *)
        echo "Unknown mode \"$MODE\""
        ;;
esac


