#!/bin/sh
################################################################
# Begin $rc_base/init.d/
#
# Description : Low-level initialization and disposition
# 
# Authors     : Simone Cociancich
# 
# Version     : 0.0.1
#
# Notes       :
#
###############################################################

. /etc/default/rc
. ${rc_functions}

SERVICE_NAME=FABtotum

case "$1" in
  start)
 	boot_msg "Starting ${SERVICE_NAME}."
	python /var/www/recovery/python/boot.py &
	true
	evaluate_retval
	;;
  stop)
	boot_msg "Stopping ${SERVICE_NAME}."
	# Turn off the lights
	(sleep 5s && echo -e "M701 S0\nM702 S0\nM703 S0" > /dev/ttyAMA0 && cat /dev/ttyAMA0 &)
	evaluate_retval
	( sleep 5s && echo M727 > /dev/ttyAMA0 &)
	;;
  restart|reload)
	${0} stop
	sleep 1
	${0} start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

