#!/bin/sh
################################################################
# Begin $rc_base/init.d/
#
# Description : 
# 
# Authors     :
# 
# Version     : 00.00
#
# Notes       :
#
###############################################################

. /etc/default/rc
. ${rc_functions}

SERVICE_NAME=FABUI

case "$1" in
  start)
 	boot_msg "Starting ${SERVICE_NAME}."
	php /var/www/fabui/script/initialize.php >> /var/log/initialize.log
	evaluate_retval
	;;
  stop)
	#boot_msg "Stopping ${SERVICE_NAME}."
	#true
	#evaluate_retval
	;;
  restart|reload)
	${0} stop
	sleep 1
	${0} start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

