#! /bin/sh
# /etc/init.d/fabui
#
### BEGIN INIT INFO
# Provides:          example
# Required-Start:    $network apache2 mysql
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start up fabui scripts
# Description:       This file should be used to construct scripts to be
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting startup script fabui"
    python /var/www/fabui/python/baud.py
	php /var/www/fabui/script/socket_server.php > /var/log/socket_server.log &
	php /var/www/fabui/script/initialize.php > /var/log/initialize.log
	python /var/www/fabui/python/flush.py > /var/log/flush.log
	php /var/www/fabui/script/boot.php > /var/log/boot.log
	python /var/www/fabui/python/monitor.py > /var/log/monitor.log &
	#sudo php /var/www/cron/instagram_feed.php > /var/log/instagram_feed.log
	#sudo php /var/www/cron/twitter_feed.php > /var/log/twitter_feed.log
	#sudo php /var/www/cron/blog_feed.php > /var/log/blog_feed.log
	#sudo php /var/www/cron/faq.php > /var/log/faq.log
    echo "Could do more here "
    ;;
  stop)
    echo "Stopping script blah"
    echo "Could do more here"
    ;;
  *)
    echo "Usage: /etc/init.d/fabui {start|stop}"
    exit 1
    ;;
esac

exit 0